version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.pgsql
    container_name: docker-postgre
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '25432:5432'
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
volumes:
  db:
    driver: local
networks:
  my-network:
    external: true
    